Feature EPL-131: Update README and build.gradle
etendosoftware/etendo_rx pull request #1
Opened 2022-07-20 16:35 UTC by pabloelena

Adding documentation about debugging

2022-07-20 16:50 UTC, juabaez approved these changes

2022-07-22 14:05 UTC, isaiasb-etendo commented on README.md
> +Examles:
Typing error

2022-07-25 10:57 UTC, sebastianbarrozo requested changes

2022-07-25 10:57 UTC, sebastianbarrozo commented on README.md
> +- Command line parameters
To keep this file clean, move it to a wiki page with the title "EtendoRX Advanced options" and replace it with the corresponding link.

2022-07-25 10:57 UTC, sebastianbarrozo commented on README.md
> +- Debug mode
Same as above

2022-07-27 18:16 UTC, isaiasb-etendo approved these changes

2022-07-27 18:43 UTC, sebastianbarrozo approved these changes

2022-07-27 18:43 UTC, merged