Feature ETO-91: Improve Jenkins pipelines
etendosoftware/etendo_rx pull request #39
Opened 2023-02-17 19:57 UTC by valeriag-etendo

2023-02-17 20:00 UTC, juabaez approved these changes

2023-02-17 20:09 UTC, szapata requested changes
Fíjate si el e-mail lo puedes sacar a una variable.

2023-02-17 20:09 UTC, szapata commented on pipelines/publish-snapshots/Jenkinsfile
> +            mail to: 'builds@smfconsulting.es',
Esta cuenta de mail hardcoded no se puede sacar a variable?

2023-02-17 20:09 UTC, szapata commented on pipelines/run-tests/Jenkinsfile
> +            mail to: 'builds@smfconsulting.es',
idem

2023-02-17 20:09 UTC, szapata commented on pipelines/run-tests/Jenkinsfile
> +            mail to: 'builds@smfconsulting.es',
fíjate que lo pones varias veces en el mismo archivo...un cambio se te multiplica por N. Es más complejo el mantenimiento.

2023-02-21 11:17 UTC, valeriag-etendo commented on pipelines/publish-snapshots/Jenkinsfile
> +            mail to: 'builds@smfconsulting.es',
Ya he probado sacarlo como variable de entorno y no es posible pasarla de ese modo.

2023-02-21 12:12 UTC, valeriag-etendo commented on pipelines/publish-snapshots/Jenkinsfile
> +            mail to: 'builds@smfconsulting.es',
Ahi encontré la forma de pasarlo como variable, ya lo corrijo

2023-02-28 15:50 UTC, RubenEtendo approved these changes

2023-02-28 19:38 UTC, szapata approved these changes

2023-02-28 20:06 UTC, merged