Feature/epl 362
etendosoftware/etendo_rx pull request #5
Opened 2022-08-15 19:36 UTC by pabloelena

The PR is against the EPL-360 because starts from there.

2022-08-16 12:47 UTC, juabaez requested changes

2022-08-16 12:47 UTC, juabaez commented on libs/com.etendorx.generate_entities/src/main/java/com/etendorx/gen/util/MetadataUtil.java
> +      var m = propertyModel.getTargetEntity().getTableName().split("_");
change the variable name for a name more declarative

2022-08-16 16:59 UTC, sebastianbarrozo approved these changes

2022-08-18 14:02 UTC, juabaez approved these changes

2022-08-18 14:04 UTC, merged