Feature EPL-683: User context in request scope
etendosoftware/etendo_rx pull request #51
Opened 2023-06-06 20:48 UTC by sebastianbarrozo

2023-06-07 11:28 UTC, juabaez requested changes

2023-06-07 11:28 UTC, juabaez commented on libs/com.etendorx.utils.auth/src/main/java/com/etendorx/utils/auth/key/context/FilterContext.java
> +    if (!active.equals("true") && !active.equals("false")) {
it's possible to use StringUtils ?

2023-06-07 11:28 UTC, juabaez commented on libs/com.etendorx.utils.auth/src/main/java/com/etendorx/utils/auth/key/context/FilterContext.java
> +    userContext.setActive("true".equals(active));
it's possible to use StringUtils ?

2023-06-07 11:28 UTC, juabaez commented on modules_core/com.etendorx.das/src/main/java/com/etendorx/das/utils/DefaultFilters.java
> +        return sql.replace((containsWhere ? WHERE : LIMIT),
here we need to check witch database is in use and use limit or rownum right ?

2023-06-07 12:03 UTC, juabaez approved these changes

2023-06-07 20:06 UTC, Matias-Bernal approved these changes

2023-06-08 01:44 UTC, Matias-Bernal approved these changes

2023-06-08 11:38 UTC, juabaez approved these changes

2023-06-08 17:38 UTC, Matias-Bernal approved these changes

2023-06-09 14:43 UTC, Matias-Bernal approved these changes

2023-06-12 11:31 UTC, valeg-etendo commented
@sebastianbarrozo Please, review the Sonar report

2023-06-15 11:36 UTC, juabaez approved these changes

2023-06-15 13:50 UTC, merged