hotfix/EPL-738: authentication request in FilterContext was fixed
etendosoftware/etendo_rx pull request #56
Opened 2023-06-22 18:54 UTC by giuliodoriEtendo

2023-06-22 20:06 UTC, Matias-Bernal requested changes

2023-06-22 20:06 UTC, Matias-Bernal commented on libs/com.etendorx.utils.auth/src/main/java/com/etendorx/utils/auth/key/context/FilterContext.java
>      if (token != null && !token.isBlank()) {
isBlank checks is not null.

2023-06-26 13:15 UTC, Matias-Bernal approved these changes

2023-06-26 17:35 UTC, juabaez approved these changes

2023-06-26 17:41 UTC, merged