Feature EPL-769: RX services can override public url list
etendosoftware/etendo_rx pull request #58
Opened 2023-07-11 12:29 UTC by sebastianbarrozo

Feature EPL-701: Allow to have multipliprojects repos

2023-07-11 14:15 UTC, Matias-Bernal approved these changes

2023-07-13 12:14 UTC, juabaez requested changes

2023-07-13 12:14 UTC, juabaez commented on modules_core/com.etendorx.auth/src/main/java/com/etendorx/auth/auth/AuthAllowedURIs.java
> +    return requestURI.startsWith(AUTH_PATH_URI);
you can use StringUtils

2023-07-17 16:24 UTC, juabaez approved these changes

2023-07-18 14:35 UTC, juabaez approved these changes

2023-07-18 18:24 UTC, merged