Feature EPL-787: Add external module an test for it
etendosoftware/etendo_rx pull request #61
Opened 2023-07-24 17:49 UTC by juabaez

2023-07-25 12:19 UTC, sebastianbarrozo requested changes
This PR must contain changes to Jenkinsfile in order to run new tests.

2023-07-25 12:19 UTC, sebastianbarrozo commented on modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/eventhandlertest/component/HibernateEventListenerComponent.java
> +        System.out.println("Pre Insert execute");
Change to log.info

2023-07-25 12:19 UTC, sebastianbarrozo commented on modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/eventhandlertest/component/HibernateEventListenerComponent.java
> +        System.out.println("Pre Update execute in second order");
Change to log.info

2023-07-25 12:19 UTC, sebastianbarrozo commented on modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/eventhandlertest/component/HibernateEventListenerComponent.java
> +        System.out.println("Pre Update execute in first order");
Change to log.info

2023-07-25 12:19 UTC, sebastianbarrozo commented on modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/eventhandlertest/component/HibernateEventListenerComponent.java
> +        System.out.println("Post Update execute");
Change to log.info

2023-07-25 12:19 UTC, sebastianbarrozo commented on modules_core/com.etendorx.das/src/test/java/com/etendorx/das/test/eventhandlertest/test/AnnotationTests.java
> +    System.out.println("Test");
Remove this println

2023-07-25 12:19 UTC, sebastianbarrozo commented on modules_test/com.etendorx.test.eventhandler/src/main/java/com/etendorx/test/eventhandler/EventHandlerTest.java
> +public class EventHandlerTest {
This application class is needed?

2023-07-25 12:24 UTC, juabaez commented
@sebastianbarrozo > This PR must contain changes to Jenkinsfile in order to run new tests.

the changes in the Jenkinsfile will be in other task

2023-08-29 14:15 UTC, RomanMagnoli approved these changes

2023-09-05 11:22 UTC, sebastianbarrozo approved these changes

2024-05-23 17:06 UTC, closed without merging